import Head from "next/head";
import Article from "../../db/models/Article";
import ArticleList from "@/components/ArticleList";
import { ArticleData } from "@/types/global";

interface HomeProps {
  articleData: ArticleData[];
}

const Home: React.FC<HomeProps> = ({ articleData }) => {
  return (
    <>
      <Head>
        <title>NewsHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ArticleList articleData={articleData} isAdmin={false} />
      </main>
    </>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  const allArticles = await Article.findAll();
  const articleData = allArticles.map((article) => ({
    id: article.id,
    title: article.title,
    content: article.content,
    author: article.author,
    category: article.category,
    image: article.image,
    createdAt: article.createdAt.toLocaleString("en-GB", {
      day: "numeric",
      month: "short",
      year: "numeric",
    }), // Convert to string
    updatedAt: article.updatedAt.toLocaleString("en-GB", {
      day: "numeric",
      month: "short",
      year: "numeric",
    }),
  }));
  return { props: { articleData } };
}

export default Home;
